### ISSUE TITLE
owid DB doesn't working 

### ISSUE THREAD

**Issue by NoamXD8** [coa-project/pycoa#204]
pycoa.setwhom("owid")
Erreur :  An error occured while parsing data of owid. This may be due to a data format modification.
<img width="1289" alt="Capture d’écran 2024-05-02 à 09 59 40" src="https://github.com/coa-project/pycoa/assets/117040017/d921352d-573b-4e1d-a87d-de83e2a8742e">

**Comment by odadoun** [comment]
The web site http://thematicmapping.org is down !
Then downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip is not anymore downloaded.
@tjbtjbtjb please have a look owid can not be parsed ...


Otherwise I have fixed 2 problems I will also push  it in the main
- structure of https://en.wikipedia.org/wiki/Community_of_Latin_American_and_Caribbean_States table
has changed
- in owid the name "Micronesia (Country)" has changed to "Micronesia (country)" keep both of them in geo ...

**Comment by odadoun** [comment]
@tjbtjbtjb try to find something for TM_WORLD_BORDERS_SIMPL-0.3.zip  please

**Comment by odadoun** [comment]
@tjbtjbtjb solved th issue now 
https://github.com/coa-project/coadata/raw/main/coastore/TM_WORLD_BORDERS_SIMPL-0.3.zip
is used
