### ISSUE TITLE
when option='sumall' which should be overwritten ?

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#83]
which='total_deaths_per_million',location=['World'],option='sumall'

gives the total_deaths not total_deaths_per_million ... so 'which' should be overwritten isn't ?

**Comment by tjbtjbtjb** [comment]
The keywords *_per_million were removed, because they cannont be managed properly, e.g. for those purposes. 

Anyway, `total_deaths_per_million` with `sumall` option actually does not provide the `total_deaths`, but sum over location of `total_deaths_per_million`, which cannot be interpreted easily.
